import requests
import random
import re
import time
import os
from bs4 import BeautifulSoup

BASE_URL = 'https://www.azlyrics.com/lyrics/beatles/'

SONG_TITLES = [
 'Glad All Over',
 'Strawberry Fields Forever',
 'Honey Pie',
 "Don't Let Me Down",
 "Mother Nature's Son",
 'Love Me Do',
 'Boys',
 'Wait',
 "I'm Only Sleeping",
 'Got To Get You Into My Life',
 'Mean Mr. Mustard',
 'She Came In Through The Bathroom Window',
 'Tomorrow Never Knows',
 'Till There Was You',
 "It's All Too Much",
 'Pepperland',
 "I Want You (She's So Heavy)",
 'Little Child',
 'Birthday',
 'Revolution',
 'Because',
 'A Day In The Life',
 'Oh! Darling',
 'Polythene Pam',
 'Hello, Goodbye',
 'Good Night',
 'Hallelujah, I Love Her So',
 "Money (That's What I Want)",
 'Ticket To Ride',
 'Michelle',
 'Martha My Dear',
 'Misery',
 'Another Girl',
 'Good Day Sunshine',
 "Can't Buy Me Love",
 'Cry Baby Cry',
 'The Ballad Of John And Yoko',
 'Anna (Go To Him)',
 'Drive My Car',
 "I'll Get You",
 'She Loves You',
 'Long Tall Sally',
 "I'll Be Back",
 'She Said, She Said',
 'For No One',
 "Don't Pass Me By",
 'Two Of Us',
 "Sgt. Pepper's Lonely Hearts Club Band",
 "I'll Be On My Way",
 "Everybody's Trying To Be My Baby",
 'Run For Your Life',
 'Too Much Monkey Business',
 'Do You Want To Know A Secret',
 'And Your Bird Can Sing',
 "You Won't See Me",
 'Lovely Rita',
 'I Feel Fine',
 'Yer Blues',
 "When I'm Sixty Four",
 'Blackbird',
 'Paperback Writer',
 'Get Back',
 "I'm So Tired",
 'Sexy Sadie',
 'I Saw Her Standing There',
 "I'm Gonna Sit Right Down And Cry (Over You)",
 'Dig A Pony',
 'Taxman',
 'Getting Better',
 'Blue Jay Way',
 'Moonlight Bay',
 "I'll Follow The Sun",
 'Her Majesty',
 'Lucy In The Sky With Diamonds',
 'Like Dreamers Do',
 'Dear Prudence',
 "Don't Bother Me",
 'You Really Got A Hold On Me',
 'You Never Give Me Your Money',
 'Not A Second Time',
 'Being For The Benefit Of Mr. Kite!',
 'Happiness Is A Warm Gun',
 'I Will',
 'Something',
 "She's Leaving Home",
 'Any Time At All',
 "You've Got To Hide Your Love Away",
 "Baby, You're A Rich Man",
 'Words Of Love',
 'A Taste Of Honey',
 'Hey Bulldog',
 'Hold Me Tight',
 'From Me To You',
 'You Like Me Too Much',
 'If I Needed Someone',
 'Pepperland Laid Waste',
 'Magical Mystery Tour',
 "She's A Woman",
 "Ain't She Sweet",
 'Yesterday',
 "There's A Place",
 'Act Naturally',
 'Think For Yourself',
 'Revolution 9',
 'How Do You Do It',
 'Rain',
 'Not Guilty',
 'Penny Lane',
 'Nowhere Man',
 'Norwegian Wood (This Bird Has Flown)',
 'Please Mister Postman',
 'Old Brown Shoe',
 "Honey Don't",
 'Sun King',
 "A Hard Day's Night",
 'Rocky Raccoon',
 "Everybody's Got Something To Hide Except Me And My Monkey",
 'We Can Work It Out',
 'The Word',
 'Tell Me What You See',
 'Back In The U.S.S.R.',
 'I Am The Walrus',
 'I Wanna Be Your Man',
 'Eight Days A Week',
 'Dizzy Miss Lizzy',
 'Every Little Thing',
 'Day Tripper',
 'I Want To Hold Your Hand',
 'Golden Slumbers',
 'I Got To Find My Baby',
 'The End',
 'Come Together',
 "Octopus's Garden",
 'Sweet Little Sixteen',
 'Love You To',
 'Yellow Submarine',
 'Come And Get It',
 'Help!',
 'Wild Honey Pie',
 'Savoy Truffle',
 'Piggies',
 'I Me Mine',
 "I'll Cry Instead",
 'Roll Over Beethoven',
 "I'm Looking Through You",
 'Twist And Shout',
 'Helter Skelter',
 'Revolution 1',
 'The Long And Winding Road',
 'Here, There And Everywhere',
 'Teddy Boy',
 'The Night Before',
 'The Fool On The Hill',
 'What Goes On',
 'Some Other Guy',
 'Ob-La-Di, Ob-La-Da',
 "It's Only Love",
 'One After 909',
 "It Won't Be Long",
 'If I Fell',
 'Only A Northern Song',
 'Hey Jude',
 'Julia',
 'I Want To Tell You',
 "I've Just Seen A Face",
 'Girl',
 'In My Life',
 'All My Loving',
 'Within You Without You',
 'Let It Be',
 "You'll Be Mine",
 'All Together Now',
 "Maxwell's Silver Hammer",
 'To Know Her Is To Love Her',
 'All Things Must Pass',
 'Tell Me Why',
 'Doctor Robert',
 'While My Guitar Gently Weeps',
 'I Should Have Known Better',
 'Carry That Weight',
 'Yellow Submarine In Pepperland',
 'All You Need Is Love',
 'Lady Madonna',
 'I Call Your Name',
 'With A Little Help From My Friends',
 'Here Comes The Sun',
 'I Need You',
 'Eleanor Rigby',
 'Glass Onion',
 "Why Don't We Do It In The Road?",
 'Across The Universe',
 'Please Please Me',
 "You're Going To Lose That Girl",
 'The Continuing Story Of Bungalow Bill',
 'Sure To Fall (In Love With You)',
 'Fixing A Hole',
 'And I Love Her'
]

headers = {
    'Referer': 'https://www.google.com/',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36',
}
for song in SONG_TITLES:
    if song in [os.path.basename(f) for f in os.listdir('beatles')]:
        continue
    clean_title = re.sub('[^a-zA-Z0-9]', '', song).lower()
    print(clean_title)
    url = BASE_URL + clean_title + '.html'
    print(url)
    if song == 'Something':
        url = url = BASE_URL + 'something-abbey' + '.html'
    resp = requests.get(url, headers=headers)
    soup = BeautifulSoup(resp.content, 'lxml')
    lyrics = soup.find('b', text='"'+song+'"').parent.find('div', class_=None).text
    with open('beatles/'+song, 'w') as f:
        f.write(lyrics)
    time.sleep(30 * random.random())